CREATE TABLE colaborador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_colaborador PRIMARY KEY (id),
    CONSTRAINT uk_colaborador_cpf UNIQUE (cpf),
    CONSTRAINT ck_colaborador_nome_nao_vazio CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_colaborador_cpf_formato CHECK (cpf ~ '^[0-9]{11}$')
);

CREATE TABLE cafe_da_manha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cafe_da_manha PRIMARY KEY (id),
    CONSTRAINT uk_cafe_da_manha_data UNIQUE (data)
);

CREATE TABLE participacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    colaborador_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_participacao PRIMARY KEY (id),
    CONSTRAINT fk_participacao_colaborador
        FOREIGN KEY (colaborador_id)
        REFERENCES colaborador (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_participacao_cafe
        FOREIGN KEY (cafe_id)
        REFERENCES cafe_da_manha (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_participacao_colaborador_cafe UNIQUE (colaborador_id, cafe_id),
    CONSTRAINT uk_participacao_id_cafe UNIQUE (id, cafe_id)
);

CREATE TABLE item_cafe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    participacao_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    nome_normalizado VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_item_cafe PRIMARY KEY (id),
    CONSTRAINT fk_item_cafe_participacao
        FOREIGN KEY (participacao_id, cafe_id)
        REFERENCES participacao (id, cafe_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_item_cafe_cafe
        FOREIGN KEY (cafe_id)
        REFERENCES cafe_da_manha (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_item_cafe_cafe_nome_normalizado UNIQUE (cafe_id, nome_normalizado),
    CONSTRAINT ck_item_cafe_nome_nao_vazio CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_item_cafe_nome_normalizado_nao_vazio CHECK (btrim(nome_normalizado) <> ''),
    CONSTRAINT ck_item_cafe_status CHECK (status IN ('PENDENTE', 'TROUXE', 'NAO_TROUXE'))
);

CREATE INDEX idx_participacao_cafe_id
    ON participacao (cafe_id);

CREATE INDEX idx_item_cafe_participacao_cafe
    ON item_cafe (participacao_id, cafe_id);

COMMENT ON COLUMN item_cafe.cafe_id IS
    'Duplicado intencionalmente para garantir unicidade do item por cafe e consistencia com a participacao por FK composta.';
